"""
How far ahead is London Underground disruption predictable, and by what?

Sweeps forecast horizons from 1 to 24 hours. At each horizon it fits a
gradient booster and compares it against a ladder of empirical lookup
baselines, so the question answered is not "does a model work" but "does a
model beat knowing the historical rate for this line at this hour".

Run:  python3 analysis/horizon_study.py
Out:  analysis/results/horizon_metrics.csv
      analysis/results/commute_decision_table.csv
      analysis/results/summary.json

Design notes, because each of these is a way to get a wrong answer that
looks plausible:

TARGET. `major_disruption` -- at least 15 minutes of unplanned Severe
Delays / Part Suspended / Suspended in the hour. Deliberately excludes
Minor Delays, which is the largest single contributor to the raw
disruption rate and is not a reason to leave earlier. Also excludes
planned engineering works (published weeks ahead, so trivially
predictable) and the scheduled overnight closure.

LEAKAGE. Features are generated by ONE function parameterised by horizon
h, so a 24-hour-ahead model can never see a 1-hour-ahead lag. The classic
mistake here is `rolling(168).mean()`, which includes the current hour --
putting the label inside its own feature. Every rolling window is taken
on an already-shifted series, so the newest observation it can see is
h hours before the target.

SERVICE HOURS ONLY. ~16% of the grid is the overnight closure, where major
disruption is near-impossible. Leaving those rows in inflates every
discrimination metric for free, so the headline evaluates on service hours.

BOOTSTRAP BY DAY, NOT BY ROW. Disruption comes in runs -- one signal
failure produces several consecutive disrupted hours, and storms or strikes
correlate across lines. Resampling rows would treat those as independent
and report confidence intervals several times too narrow. The uplift CI
resamples whole days.
"""

import json
import os
import warnings
from datetime import date

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import average_precision_score, brier_score_loss, roc_auc_score

warnings.filterwarnings("ignore")

HOURLY = "data/hourly.csv"
OUTDIR = "analysis/results"
TARGET = "major_disruption"
LEAD_TIMES = [0, 1, 2, 3, 6, 12, 24]   # hours of genuine lead before the target hour STARTS

TRAIN_END = "2025-12-31"
VAL_END = "2026-04-30"          # used for early stopping, not decoration
COMMUTE_LINES = ["victoria", "northern", "piccadilly", "c-and-h"]
COMMUTE_HOURS = [7, 8, 9]
ALERT_BUDGET = 0.10            # fire on at most 10% of opportunities

# England & Wales bank holidays, gov.uk. Hardcoded rather than fetched so the
# script has no network dependency and gives identical results on re-run.
BANK_HOLIDAYS = {
    "2022-01-03","2022-04-15","2022-04-18","2022-05-02","2022-06-02","2022-06-03",
    "2022-08-29","2022-09-19","2022-12-26","2022-12-27",
    "2023-01-02","2023-04-07","2023-04-10","2023-05-01","2023-05-08","2023-05-29",
    "2023-08-28","2023-12-25","2023-12-26",
    "2024-01-01","2024-03-29","2024-04-01","2024-05-06","2024-05-27","2024-08-26",
    "2024-12-25","2024-12-26",
    "2025-01-01","2025-04-18","2025-04-21","2025-05-05","2025-05-26","2025-08-25",
    "2025-12-25","2025-12-26",
    "2026-01-01","2026-04-03","2026-04-06","2026-05-04","2026-05-25","2026-08-31",
    "2026-12-25","2026-12-28",
}


# ------------------------------------------------------------------ loading
def load() -> pd.DataFrame:
    df = pd.read_csv(HOURLY, parse_dates=["hour_utc"])
    df = df.sort_values(["line_id", "hour_utc"]).reset_index(drop=True)

    df["is_holiday"] = df["date"].isin(BANK_HOLIDAYS).astype(int)
    df["month"] = df["hour_utc"].dt.month
    df["dow_num"] = pd.Categorical(
        df["dow_local"],
        categories=["Monday", "Tuesday", "Wednesday", "Thursday",
                    "Friday", "Saturday", "Sunday"],
    ).codes
    df["line_code"] = pd.Categorical(df["line_id"]).codes
    # Service hours: the overnight closure is not a forecasting problem.
    df["in_service"] = (df["closed_min"] < 30).astype(int)
    return df


def add_lags(df: pd.DataFrame, lead: int) -> pd.DataFrame:
    """Features knowable `lead` hours before the target hour STARTS.

    The off-by-one here is the whole ballgame. To forecast the hour starting
    08:00 with `lead` hours of warning, the prediction is issued at
    08:00 - lead. At that instant the most recently COMPLETED hour is the one
    starting 08:00 - lead - 1, so the newest usable lag is shift(lead + 1),
    not shift(lead).

    Using shift(lead) would mean reading the outcome of an hour that has not
    finished yet at issue time. At lead=1 that inflates the result enormously,
    because disruption comes in runs and the immediately preceding hour is by
    far the strongest single predictor.

    lead = 0 is kept deliberately as a reference point: the forecast issued at
    the moment the target hour begins. That is the "is the line broken right
    now" question the TfL app already answers, and it is the ceiling any
    genuine forecast is measured against.
    """
    out = df.copy()
    g = out.groupby("line_id", sort=False)
    newest = lead + 1          # see docstring

    # Point lags: the last observation available, and two before it.
    for extra in (0, 1, 2):
        out[f"lag_{extra}"] = g[TARGET].shift(newest + extra)
    out["lag_min_0"] = g["major_min"].shift(newest)
    out["lag_anydis_0"] = g["any_disruption"].shift(newest)

    # Trailing rates, all ending at the newest complete hour.
    shifted = g[TARGET].transform(lambda s: s.shift(newest))
    out["_shift"] = shifted
    for win, name in ((24, "24h"), (168, "7d"), (720, "30d")):
        out[f"rate_{name}"] = out.groupby("line_id", sort=False)["_shift"].transform(
            lambda s, w=win: s.rolling(w, min_periods=max(6, w // 8)).mean()
        )
    out = out.drop(columns=["_shift"])

    # Planned works are published weeks ahead, so they ARE known at issue time
    # regardless of horizon -- one of the few genuinely available signals.
    out["planned_known"] = (out["planned_min"] > 0).astype(int)
    return out


FEATURES = [
    "line_code", "hour_local", "dow_num", "is_weekend_local", "month",
    "is_holiday", "planned_known",
    "lag_0", "lag_1", "lag_2", "lag_min_0", "lag_anydis_0",
    "rate_24h", "rate_7d", "rate_30d",
]
CALENDAR_ONLY = [
    "line_code", "hour_local", "dow_num", "is_weekend_local", "month",
    "is_holiday", "planned_known",
]


# ---------------------------------------------------------------- baselines
def lookup_baseline(train: pd.DataFrame, test: pd.DataFrame, keys, shrink=0.0):
    """Empirical rate per cell, fitted on train only.

    With shrink > 0 this is empirical-Bayes style: each cell is pulled toward
    the global rate in proportion to how little data it has, so a cell with
    three observations doesn't get to claim a rate of 1.0. This makes the
    baseline genuinely harder to beat, which is the point of a baseline.
    """
    prior = train[TARGET].mean()
    grp = train.groupby(keys, observed=True)[TARGET].agg(["mean", "count"])
    if shrink > 0:
        grp["rate"] = (grp["mean"] * grp["count"] + prior * shrink) / (grp["count"] + shrink)
    else:
        grp["rate"] = grp["mean"]
    pred = test[keys].merge(
        grp["rate"].reset_index(), on=keys, how="left"
    )["rate"].to_numpy()
    return np.where(np.isnan(pred), prior, pred)


# ------------------------------------------------------------------ metrics
def recall_at_budget(y, p, budget=ALERT_BUDGET):
    """Recall when alerting on the top `budget` fraction of predictions.

    This is the metric that maps to the product: you have a limited number of
    mornings you can cry wolf on before being ignored. Also returns the
    precision you get for that spend.
    """
    n_alert = max(1, int(len(p) * budget))
    idx = np.argsort(-p)[:n_alert]
    caught = y[idx].sum()
    total = y.sum()
    return (caught / total if total else np.nan,
            caught / n_alert)


def metrics(y, p):
    y = np.asarray(y); p = np.asarray(p)
    rec, prec = recall_at_budget(y, p)
    return {
        "pr_auc": average_precision_score(y, p),
        "roc_auc": roc_auc_score(y, p),
        "brier": brier_score_loss(y, p),
        "recall_at_10pct": rec,
        "precision_at_10pct": prec,
        "base_rate": y.mean(),
    }


def block_bootstrap_uplift(test, y, p_model, p_base, n=200, seed=0):
    """CI on (model PR-AUC - baseline PR-AUC), resampling whole days.

    Row-level resampling would assume each line-hour is independent. It isn't:
    one incident spans several hours and often several lines, so row
    bootstrap gives intervals far too narrow.
    """
    rng = np.random.default_rng(seed)
    days = test["date"].to_numpy()
    uniq = np.unique(days)
    # Precompute row indices per day once.
    by_day = {d: np.flatnonzero(days == d) for d in uniq}
    diffs = []
    for _ in range(n):
        pick = rng.choice(uniq, size=len(uniq), replace=True)
        idx = np.concatenate([by_day[d] for d in pick])
        yb = y[idx]
        if yb.sum() == 0 or yb.sum() == len(yb):
            continue
        diffs.append(average_precision_score(yb, p_model[idx])
                     - average_precision_score(yb, p_base[idx]))
    lo, hi = np.percentile(diffs, [2.5, 97.5])
    return float(np.mean(diffs)), float(lo), float(hi)


# --------------------------------------------------------------------- main
def main():
    os.makedirs(OUTDIR, exist_ok=True)
    base = load()
    print(f"grid: {len(base):,} line-hours   "
          f"{base['hour_utc'].min().date()} -> {base['hour_utc'].max().date()}")
    print(f"target `{TARGET}`: {100*base[TARGET].mean():.2f}% of all hours, "
          f"{100*base.loc[base.in_service==1, TARGET].mean():.2f}% of service hours\n")

    rows, commute_rows, summary = [], [], {}

    for h in LEAD_TIMES:
        df = add_lags(base, h)
        df = df.dropna(subset=FEATURES)
        df = df[df.in_service == 1]                 # service hours only

        train = df[df["date"] <= TRAIN_END]
        val = df[(df["date"] > TRAIN_END) & (df["date"] <= VAL_END)]
        test = df[df["date"] > VAL_END].reset_index(drop=True)
        y_tr, y_va, y_te = (d[TARGET].to_numpy() for d in (train, val, test))

        # --- baselines, fitted on train only
        preds = {
            "base_rate": np.full(len(test), y_tr.mean()),
            "lookup_line": lookup_baseline(train, test, ["line_id"]),
            "lookup_line_hour": lookup_baseline(train, test, ["line_id", "hour_local"]),
            "lookup_line_hour_dow": lookup_baseline(
                train, test, ["line_id", "hour_local", "dow_num"]),
            "lookup_shrunk": lookup_baseline(
                train, test, ["line_id", "hour_local", "dow_num"], shrink=50),
        }

        # --- calendar-only model: isolates how much the model class adds
        #     over the lookup table when both see the same information
        cal = HistGradientBoostingClassifier(
            max_iter=400, learning_rate=0.06, early_stopping=True,
            validation_fraction=None, random_state=0)
        cal.fit(pd.concat([train, val])[CALENDAR_ONLY], np.concatenate([y_tr, y_va]))
        preds["gbm_calendar"] = cal.predict_proba(test[CALENDAR_ONLY])[:, 1]

        # --- full model, early stopping on the val split
        gbm = HistGradientBoostingClassifier(
            max_iter=600, learning_rate=0.06, early_stopping=True,
            validation_fraction=None, random_state=0)
        gbm.fit(train[FEATURES], y_tr)
        preds["gbm_full"] = gbm.predict_proba(test[FEATURES])[:, 1]

        best_base = max(
            ("lookup_line_hour_dow", "lookup_shrunk", "lookup_line_hour"),
            key=lambda k: average_precision_score(y_te, preds[k]))

        print(f"--- lead {h}h  (train {len(train):,} / test {len(test):,}, "
              f"test base rate {100*y_te.mean():.2f}%)")
        for name, p in preds.items():
            m = metrics(y_te, p)
            rows.append({"lead_h": h, "model": name, **m})
            mark = "  <- best baseline" if name == best_base else ""
            print(f"    {name:<22} PR-AUC {m['pr_auc']:.4f}  ROC {m['roc_auc']:.4f}  "
                  f"Brier {m['brier']:.4f}  R@10% {m['recall_at_10pct']:.3f}{mark}")

        mean, lo, hi = block_bootstrap_uplift(
            test, y_te, preds["gbm_full"], preds[best_base])
        beats = lo > 0
        print(f"    uplift over {best_base}: {mean:+.4f} PR-AUC "
              f"[{lo:+.4f}, {hi:+.4f}] {'SIGNIFICANT' if beats else 'not significant'}\n")
        summary[f"lead_{h}h"] = {
            "best_baseline": best_base,
            "uplift_pr_auc": mean, "ci_low": lo, "ci_high": hi,
            "significant": bool(beats),
            "test_base_rate": float(y_te.mean()),
        }

        # --- the slice the product would actually live in
        mask = (test["line_id"].isin(COMMUTE_LINES)
                & test["hour_local"].isin(COMMUTE_HOURS)
                & (test["is_weekend_local"] == 0))
        sl = test[mask]
        if len(sl) > 50 and sl[TARGET].sum() > 5:
            ys = sl[TARGET].to_numpy()
            ps = preds["gbm_full"][mask.to_numpy()]
            for thr in (0.05, 0.10, 0.15, 0.20, 0.30):
                fire = ps >= thr
                commute_rows.append({
                    "lead_h": h, "threshold": thr,
                    "fires_pct": 100 * fire.mean(),
                    "precision": ys[fire].mean() if fire.sum() else np.nan,
                    "recall": ys[fire].sum() / ys.sum() if ys.sum() else np.nan,
                    "n": len(ys), "base_rate": ys.mean(),
                })

    pd.DataFrame(rows).to_csv(f"{OUTDIR}/horizon_metrics.csv", index=False)
    pd.DataFrame(commute_rows).to_csv(f"{OUTDIR}/commute_decision_table.csv", index=False)
    with open(f"{OUTDIR}/summary.json", "w") as f:
        json.dump({"generated": str(date.today()), "target": TARGET,
                   "horizons": summary}, f, indent=2)
    print(f"wrote {OUTDIR}/horizon_metrics.csv, commute_decision_table.csv, summary.json")


if __name__ == "__main__":
    main()
